language: node_js
node_js:
cache: npm
env:
  - NODE_ENV=test
install:
  - npm install
  - npm install -g codecov
before_script:
  - npm run lint -- --quiet
script:
  - npm run test
  - codecov
after_script:
  - npm run bundlesize